# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UI-DataScience
email: 
description: > # this means to ignore newlines until "baseurl:"
  We began as the Laboratory for Cosomological Data Mining 
  and have grown to include more than 20 graduate and undergraduate 
  student researchers from a variety of disciplines including 
  Statistics, Computer Science, Physics, and Astronomy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  UI-DataScience

# Build settings
markdown: kramdown
